name: Check 6138

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Check branches
        run: |
          git ls-remote --heads https://github.com/tuanhackmap1-bot/Xiaomi_Kernel_OpenSource.git

      - name: Check 6138
        run: |
          git ls-remote --heads https://github.com/tuanhackmap1-bot/Xiaomi_Kernel_OpenSource.git | grep '138' || true
          git ls-remote --tags https://github.com/tuanhackmap1-bot/Xiaomi_Kernel_OpenSource.git | grep '138' || true
